### ISSUE TITLE
로그인 로직 토론

### ISSUE THREAD

**Issue by argon1025** [TIL-Log-lab/Tilog-server-node-v2#17]
# ![기타](https://img.shields.io/badge/기타사항-else-green?style=for-the-badge&logo=GitHub&logoColor=white)

## 토큰 관리 테이블 구성
```
userAuth {
refreshToken   string
userAgent      string
userIp         string
}
```
## 액세스토큰
액세스 토큰은 10분 만료를 기준으로 한다
만료되었을 경우 리프레시 토큰으로 재발급한다

## 리프레시토큰으로 액세스토큰을 발급받는 로그인 플로우
```
1. 토큰 복호화 시도 -> 실패시 권한 없음 에러
2. userAuth 테이블에서 해당 토큰에 대한 정보를 가져온다 -> 실패시 권한 없음 에러
3. 데이터베이스에 기록된 토큰 만료 시간과 현재 시간을 체크한다 -> 만료되었을 경우 토큰을 삭제
4. requestData.userAgent와 userAuth 테이블에 기록된 userAgent 기록이 맞는지 대조한다 -> 틀릴시 해킹으로 판단 토큰삭제
5. 유저 아이디에 맞는 액세스 토큰을 발급하고 리턴 
```

검토 및 보충 부탁드립니다!

**Comment by Daphne-dev** [comment]
리프레시 토큰 만료 시간은 언제까지 인가요? 
@argon1025

**Comment by argon1025** [comment]
@Daphne-dev 
리프레시 토큰 만료 기간은 일주일 정도로 하던지 한달 정도로 길게 잡았으면 해요

**Comment by MINJE-98** [comment]
# 로그인 로직 시각화
로그인 로직을 시각화 해보았습니다.
## First Login(최초 로그인)
![First Login](https://user-images.githubusercontent.com/56459078/163403517-389d8ed3-2eb1-4bb7-b531-3d0f3600737d.png)
## AccessToken Alive
![AccessToken Alive](https://user-images.githubusercontent.com/56459078/163403892-31403f56-b47a-4393-bc66-11be497a1ae5.png)
## AccessToken Expired
![AccessToken Expired](https://user-images.githubusercontent.com/56459078/163403934-065eb663-aa44-4456-b758-225ea90d6f7a.png)
## RefreshToken Expired
![RefreshToken Expired](https://user-images.githubusercontent.com/56459078/163403961-29431f81-a381-4b47-b3b4-244095209144.png)

**Comment by argon1025** [comment]
#19 에서 구현되었습니다

**Comment by argon1025** [comment]
#22 에서 마지막으로 토큰 인증이 구현되었습니다. 이슈를 종료합니다
