### ISSUE TITLE
Exception-filter, Logger 개선

### ISSUE THREAD

**Issue by argon1025** [TIL-Log-lab/Tilog-server-node-v2#25]
# ![기능 추가](https://img.shields.io/badge/기능추가-feature-blue?style=for-the-badge&logo=addThis&logoColor=white)

## 자세한 내용
- prisma 에러 대응
- 모든 에러에 대한 콘솔 로그 제공
- 로그 활성화 옵션 추가

**Comment by Daphne-dev** [comment]
이거 필요하다고 생각했는데 좋네용 
prisma에서 에러 터졌을때 에러 스택 내용이 안떠서 좀 헤맸습니다..

**Comment by argon1025** [comment]
#57 에서 계속합니다
