### ISSUE TITLE
Prisma <-> OpenAPI undifeind null 대응에 대해서

### ISSUE THREAD

**Issue by argon1025** [TIL-Log-lab/Tilog-server-node-v2#29]
# ![기타](https://img.shields.io/badge/기타사항-else-green?style=for-the-badge&logo=GitHub&logoColor=white)
## 자세한 내용

Prisma Type
users['mailAddress'] => `string | null` 타입을 반환합니다

Prisma Select Result
```
[
  {
    id: 1,
    userName: 'argon1025',
    proFileImageURL: 'https://avatars.githubusercontent.com/u/55491354?v=4',
    mailAddress: null,
    provider: 'GITHUB',
    providerServiceId: 'MDQ6VXNlcjU1NDkxMzU0',
    createdAt: 2022-04-13T15:39:36.000Z,
    updatedAt: 2022-04-16T06:14:07.000Z,
    deletedAt: null
  }
]
```
데이터가 없을 경우 Null을 반환합니다

----
DTO 
```
export class GetUserInfoResponseDto {

  mailAddress: users['mailAddress']; // Prisma interface type

  constructor(required: Required<GetUserInfoResponseDto>) {
    Object.assign(this, required);
  }
}
```
Prisma와 DTO간 타입 무결성을 위해서 통일할 경우
<img width="302" alt="image" src="https://user-images.githubusercontent.com/55491354/163707744-04d01d48-01ad-4833-9aaa-f99ac81a66bf.png">

Swagger OpenAPI에서 Object로 표기되는 현상이 발생합니다
그래서 유틸리티 타입을 통해서  NonNullable<users['mailAddress']> 하고 swagger에서 nullable 옵션을 활성화 해야합니다

기존에 컨벤션대로 undifeind를 리턴하기 위해서는 Prisma 출력 결과도 추가 연산을 통해서 undifeind로 변경하는 작업이 필요한데 저희가 리턴타입을 어떻게 정하느냐에 따라서 DTO 코드도 변경해야하는 작업이 필요한데 어떻게 할껀지 정해봅시다!☄️

**Comment by argon1025** [comment]
type test {
 list?:[]
}

type test {
 list:[] | null
}

둘중 어떤식으로 OpenAPI-SDK 응답 인터페이스로 제공되는것이 좋을지 중점을 두고 생각해야할 것 같습니다

**Comment by Daphne-dev** [comment]
데이터가 없는 경우 모두 Null로 통일하는 것으로 하면 어떨까요?

**Comment by argon1025** [comment]
빈데이터에 대해서 모두 NULL로 처리하기로 결정되었습니다
