### ISSUE TITLE
PR 오픈 시 comments에 기타 제안 사항 항목 추가

### ISSUE THREAD

**Issue by Daphne-dev** [TIL-Log-lab/Tilog-server-node-v2#47]
# ![기타](https://img.shields.io/badge/기타사항-else-green?style=for-the-badge&logo=GitHub&logoColor=white)

## 자세한 내용

PR 오픈 시 예시 comments에 `기타 제안 사항`을 추가해주세요.
개발 진행 후 의문이 들거나 애매한 사항에 대해 코멘트를 남길 일이 생길 수 있을 거 같습니다.

**Comment by argon1025** [comment]
좋습니다~ 잠시 후에 반영하겠습니다
추가로 PR 된 후 개발자들이 참고해야할 사항 `이후 조치` 란도 함께 생성하는게 좋아 보여요
필요한 이유는 다음과 같습니다
- Prisma 마이그레이션 필요 여부를 다른 개발자들에게 알린다
- OpenAPI 배포에 관련된 사항을 다른 개발자들에게 알린다
