### ISSUE TITLE
front에서 open-api를 사용하는데 문제가 있습니다.

### ISSUE THREAD

**Issue by MINJE-98** [TIL-Log-lab/Tilog-server-node-v2#69]
# ![오류](https://img.shields.io/badge/오류발생-error-red?style=for-the-badge&logo=Cachet&logoColor=white)

## 자세한 내용

# 원인

[NextJS에서 루트 디렉터리 외부에서 ts/tsx 파일을 가져올 수 없습니다.](https://github.com/vercel/next.js/issues/19928#issuecomment-740689375)

# 제안
두가지 방법을 제안합니다.
1. open-api를 모듈화 하는 과정에서 es6로 컴파일하고, 타입추론이 가능하게 변경해야합니다.
2. [next-transpile-module](https://www.npmjs.com/package/next-transpile-modules)을 사용합니다.

**Comment by argon1025** [comment]
기존 Typescript 파일 그대로 배포되던 방식에서
Typescript -> javascript 빌드 후 d.ts파일을 포함하여 패키지를 배포했습니다

**Comment by argon1025** [comment]
문제가 해결되었기때문에 이슈를 종료합니다

**Comment by argon1025** [comment]
@MINJE-98 OpenAPI 패키지 업데이트 해 주세요!
