### ISSUE TITLE
특정 유저 검색 엔드포인트 추가

### ISSUE THREAD

**Issue by MINJE-98** [TIL-Log-lab/Tilog-server-node-v2#84]
# ![기능 추가](https://img.shields.io/badge/기능추가-feature-blue?style=for-the-badge&logo=addThis&logoColor=white)

## 자세한 내용

유저 블로그에 접근할시 접근한 유저에 대한 유저 정보가 필요합니다.

**Comment by argon1025** [comment]
요구사항을 구체화 해 주세요!

**Comment by MINJE-98** [comment]
예를 들어 
A이라는 유저의 블로그에 접속하게 되면 A사용자에 대한 정보가 필요합니다. A의 정보를 가져오기 위해서 추가적인 엔드포인트가 필요합니다. (V1의 [해당](https://api.tilog.io/api/#/Users/UsersController_userInfo) 엔드포인트와 동일한 엔드포인트가 필요합니다)

**Comment by argon1025** [comment]
@MINJE-98 
아! 확인했습니다
작업 후 PR 드리겠습니다
