### ISSUE TITLE
[버그] create comment

### ISSUE THREAD

**Issue by MINJE-98** [TIL-Log-lab/Tilog-server-node-v2#87]
# ![오류](https://img.shields.io/badge/오류발생-error-red?style=for-the-badge&logo=Cachet&logoColor=white)

## 자세한 내용

replyTo를 open api에서 null로 처리하면 backend측에서 에러가 발생합니다.

### 제안
replyTo를 string | undefined로 수정

**Comment by Daphne-dev** [comment]
@MINJE-98 확인했습니다. 작업 후 노티 드릴게요.
